# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MYb_jkDhJDS7MU9FYT_u_YVe3sMxSzTv

Submitted by Oran Binyaminovich
Lecturer Dr Uri Itai
Teaching Assistant Gabriella Vagner
Dataset Selection:
I chose the California Housing dataset
The data comes from the 1990 California census
It was collected by the US Census Bureau to check housing prices based on location and demographics
The dataset has 8 numerical featurs:
MedInc - median income
HouseAge - median house age
AveRooms - average rooms
AveBedrms - average bedrooms
Population - block population
AveOccup - average household members
Latitude - block latitude
Longitude - block longitude
Limitations: The data is from 1990 so it is very old and it groups data by blocks instead of individual houses.
"""

import pandas as pd
from sklearn.datasets import fetch_california_housing
california = fetch_california_housing(as_frame=True)
df = california.data
df.head()

"""Exploratory Data Analysis:
I will now plot the data to see distributions and find outliers
I will also make a correlation matrix to see how features relate
Heavy tails in Population show natural extreme values and not necesarily noise.
"""

print(df.info())
print(df.describe())
print(df.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix")
plt.show()
for col in df.columns:
    fig, axes = plt.subplots(1, 2, figsize=(10, 3))
    sns.histplot(df[col], kde=True, ax=axes[0])
    sns.boxplot(x=df[col], ax=axes[1])
    plt.suptitle(f"{col} - Skew: {df[col].skew():.2f} Kurtosis: {df[col].kurtosis():.2f}")
    plt.show()

"""Dimensionality Reduction:
I will scale the data and apply PCA
The scree plot shows how many components we need
We need about 6 components to keep most of the information.
"""

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)
pca = PCA()
pca.fit(X_scaled)
plt.plot(range(1, 9), pca.explained_variance_ratio_, marker='o', label='Variance')
plt.plot(range(1, 9), np.cumsum(pca.explained_variance_ratio_), marker='x', label='Cumulative')
plt.legend()
plt.show()
pca_2d = PCA(n_components=2).fit_transform(X_scaled)
plt.scatter(pca_2d[:,0], pca_2d[:,1], alpha=0.3, s=2)
plt.title("2D PCA")
plt.show()
pca_3d = PCA(n_components=3).fit_transform(X_scaled)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(pca_3d[:,0], pca_3d[:,1], pca_3d[:,2], alpha=0.3, s=2)
plt.title("3D PCA")
plt.show()

"""Clustering Analysis:
I will use KMeans DBSCAN and Hierarchical clustering
I will also cluster the features to see hidden dependencies
Clustering features helps find redundant variables like rooms and bedrooms
Average variance is not always good for density models like DBSCAN so I will use Silhouete Score as an alternative.
"""

from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score
kmeans = KMeans(n_clusters=3, random_state=42).fit_predict(X_scaled)
dbscan = DBSCAN(eps=0.5, min_samples=5).fit_predict(X_scaled)
hierarchical = AgglomerativeClustering(n_clusters=3).fit_predict(X_scaled)
plt.scatter(pca_2d[:,0], pca_2d[:,1], c=kmeans, cmap='viridis', s=2, alpha=0.5)
plt.title("KMeans on 2D PCA")
plt.show()
kmeans_features = KMeans(n_clusters=3, random_state=42).fit_predict(X_scaled.T)
for i in range(3):
    print(f"Feature Cluster {i}: {df.columns[kmeans_features == i].tolist()}")
print(f"Silhouette Score: {silhouette_score(X_scaled, kmeans):.2f}")

"""Detection and Comparison:
I will use Z Score Isolation Forest and Local Outlier Factor
Z Score assumes normal distribution and fails in high dimensions
Isolation forest is better for high dimensions
LOF finds local anomalies based on neighborhood density.
"""

from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from scipy.stats import zscore
z_scores = np.abs(zscore(X_scaled))
anomalies_z = (z_scores > 3).any(axis=1)
iso = IsolationForest(contamination=0.05, random_state=42)
anomalies_iso = iso.fit_predict(X_scaled) == -1
lof = LocalOutlierFactor(n_neighbors=20, contamination=0.05)
anomalies_lof = lof.fit_predict(X_scaled) == -1
print(f"Z-Score anomalies: {anomalies_z.sum()}")
print(f"Isolation Forest anomalies: {anomalies_iso.sum()}")
print(f"LOF anomalies: {anomalies_lof.sum()}")

"""Critical Analysis:
Anomaly detection is hard because of the curse of dimensionality
In high dimensions distaances between points become very similar
We must be careful with false alarms in real systems because they cause alert fatigue and privacy issues.
"""